### ISSUE TITLE
横屏模式下更新按钮看不到

### ISSUE THREAD

**Issue by jp1017** [vell001/BetaSDKDemo#4]
![device-2017-03-17-110759](https://cloud.githubusercontent.com/assets/7868514/24027383/1f05bca6-0b02-11e7-8df9-f74759a6d00a.png)

**Comment by jp1017** [comment]
https://github.com/BuglyDevTeam/Bugly-Android-Demo/issues/11

**Comment by vell001** [comment]
你好，请使用新版sdk看看哈，https://bugly.qq.com/v2/downloads
